sensor-range: 8
chest-shield-id: 0
trap-door-range: 6
send-sign-search-distance: 7
send-signs-remove-original-text: false
send-overwrites-existing-text: true
allow-command-sends: true
flameturret-block-id: NETHERRACK
chest-shield-range: 5
send-overwrites-commands: true
teleblock-string: A mysterious force blocks your teleportation!
replace-trapdoor-blocks-on-power-off: true
teleblock-shield-range: 10
allowed-trapdoor-blocks: DIRT,COBBLESTONE,STONE,WOOD,GRASS,SAND,GLASS,SANDSTONE
flameturret-range: 5
teleblock-shield-block-Id: OBSIDIAN
webturret-block-id: GLOWSTONE
webturret-range: 5
web-dissipation-time: 10
webturret-cost: 0.0
flameturret-cost: 0.0
sensor-cost: 0.0
chestshield-cost: 0.0
teleblockshield-cost: 0.0
sendsign-cost: 0.0
equalsign-cost: 0.0
trapdoor-cost: 0.0
transmitter-cost: 0.0
receiver-cost: 0.0
arrowturret-block-id: BRICK
sensor-broadcast-dist: 75
msg-builder-only: true
arrowturret-cost: 0.0
telepad-block-id: IRON_BLOCK
telepad-tower-id: IRON_BLOCK
telepad-tower-top-id: DIAMOND_BLOCK
telepad-support-id: LAPIS_BLOCK
telepad-max-height: 32
telepad-max-length: 32
radio-range: 0
radio-cross-world: true